### ISSUE TITLE
Error while runnning setup.sh in Cloud9

### ISSUE THREAD

**Issue by RogerThat000** [aws-samples/aws-lambda-java-workshop#525]
I encountered a problem while working on the workshop using Cloud9 with admin access IAM role. The script ./setup.sh failed to resize the EBS volume on EC2. I checked the service role that was created by Cloud9 - AWSServiceRoleForAWSCloud9, and I found out that it was missing the permission for DescribeVolumeModifications. How can I fix this issue? as service role cant be edited.

Another issue , after I comment out resize in setup.sh, I am able to proceed further and continue the unicorn -store lab but while running setup-infrastructure.sh, I get deployment failed.
Error : Unable to resolve AWS account to use , how do I set which account to use through Cloud9 environment ?
Need help with fixing this issue too.

**Comment by deki** [comment]
Hi @RogerThat000, 
thanks for raising this. The script should be executed with a role that has AdministratorAccess and not with the Cloud9 service role. You can run `aws sts get-caller-identity` to identify what's currently in use. 

Looking at our instructions we are missing that part for the setup in an own AWS account right now. You can follow the setup instructions from a different workshop https://catalog.workshops.aws/eks-logging/en-US/setup/3-cloud9-env#grant-iam-role-to-an-aws-cloud9-instance until we've fixed it.

**Comment by RogerThat000** [comment]
-=PROPRIETARY=-

Thank you for your reply and with the set-up instructions you provided I was able to complete the steps without IAM access errors.

Also is there any way , we ( our team ) can complete the workshop without creating public Subnet and EIP on public subnet as our SCPs are blocking it causing Unicorn Infrastructure to fail.

Regards,
@RogerThat000<https://github.com/RogerThat000>




-=PROPRIETARY=-

**Comment by maschnetwork** [comment]
Hi @RogerThat000,

the core infrastrucute setup is defined in this Stack: https://github.com/aws-samples/aws-lambda-java-workshop/blob/main/labs/unicorn-store/infrastructure/cdk/src/main/java/com/unicorn/core/InfrastructureStack.java

You can define your additional VPC requirements in this Stack by only defining private subnets, for example. See  https://docs.aws.amazon.com/cdk/api/v2/java/software/amazon/awscdk/services/ec2/Vpc.html for reference.

Best,
Max
