### ISSUE TITLE
GraalVM sample for a restful spring application.

### ISSUE THREAD

**Issue by emmanuelU17** [aws-samples/aws-lambda-java-workshop#783]
Hey I have been trying to convert and deploy software/unicorn-store-spring to graalvm native image to lambda but I can't figure it out yet. I have been at it for some days now so if a sample can be made. Thank you in advance.

**Comment by deki** [comment]
Hi @emmanuelU17, 
were you following the description in our workshop https://catalog.workshops.aws/java-on-aws-lambda/en-US/01-migration/graalvm? Which step didn't work for you?

If you prefer to join a direct call with us, please reach out via your AWS account team (or using https://aws.amazon.com/contact-us/sales-support/ in case you don't know).

**Comment by emmanuelU17** [comment]
Hi @deki,
I am indeed following the description in the workshop. I can see from my logs, my application booted up but it timed out because there was no communication between lambda and my application. The repo below is my sample [https://github.com/emmanuelU17/server-side-event/tree/lambda/backend](url)

**Comment by deki** [comment]
Thanks for sharing your repo. The way you've implemented it is actually not supported right now, but it's already being worked on (see https://github.com/aws/serverless-java-container/issues/335 and https://github.com/aws/serverless-java-container/pull/739).

To get it running today you'd need to follow our sample https://github.com/aws-samples/aws-lambda-java-workshop/tree/main/labs/unicorn-store/software/alternatives/unicorn-store-spring-graalvm and implement a Spring Cloud Function Handler.

I'll keep this issue open until an updated sample is available (likely beginning of next month).

**Comment by emmanuelU17** [comment]
Ohh thank you for the clarification. I been at this for some days now to the extent I almost started questioning myself. I'll definitely be on the lookout for see aws/serverless-java-container#335 and aws/serverless-java-container#739 and this issue.

Thank you again for the clarification.

**Comment by emmanuelU17** [comment]
Looks like [https://github.com/aws/serverless-java-container/issues/335](url) has solved this issue but before it is closed I got a quick question. What if I want to my source code to be saved in ECR instead of S3. For one

1. Is this possible? I mean deploying via ECR instead of S3.
2. If it is possible, would the entry point in my Dockerfile look something like this ENTRYPOINT ["/app/pet-store-native"] (ps. I can update this issue to what my Dockerfile would look like)?

**Comment by emmanuelU17** [comment]
Hey, I finally was able to deploy my source code for another project based on the example. From sample example. I would like to try a different way of deployment to lambda via ECR. I understand because I am using a custom runtime, I'll have to define a bootstrap file (which I did in the root folder). I can successfully deploy to ECR but as of rn I am manually deploying to lambda. The issue I am having is my application doesn't start up on lambda even though I defined the EntryPoint in my Dockerfile.ecr to my bootstrap file . If you do not mind, can you take a look at my [repo](https://github.com/emmanuelU17/server-side-event/tree/lambda/backend) and guide me on what I am doing wrong.

**Comment by emmanuelU17** [comment]
Never mind I got it figured out. Realized I was missing copying bytecode into `${LAMBDA_TASK_ROOT}`. These examples helped for anyone finding issues.[Python example](https://repost.aws/knowledge-center/lambda-container-images) and [R example](https://mdneuzerling.com/post/r-on-aws-lambda-with-containers/)
